spring:
  application:
    name: hash-service
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: postgres
    password: zxca
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8074